# This is a basic workflow to help you get started with Actions

# <https://www.getzola.org/documentation/deployment/github-pages/>

# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    name: sawthinkar/blog-v2
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - uses: actions/checkout@master
    # Build & deploy
    - name: sawthinkar/blog-v2
      uses: sawthinkar/blog-v2@main
      env:
        # Target branch
        PAGES_BRANCH: main
        # Provide personal access token
        TOKEN: d536eee5250520984c618cd8814722b3660a1577 
